<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace GPBMetadata;

class Demo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0010a0a64656d6f2e70726f746f120664656d6f7062221c0a0c48656c" .
            "6c6f52657175657374120c0a046e616d65180120012809221d0a0a48656c" .
            "6c6f5265706c79120f0a076d65737361676518012001280932450a0b4465" .
            "6d6f5365727669636512360a0853617948656c6c6f12142e64656d6f7062" .
            "2e48656c6c6f526571756573741a122e64656d6f70622e48656c6c6f5265" .
            "706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

