<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8020a0c636f6d6d6f6e2e70726f746f1208636f6d6d6f6e706222370a" .
            "0e5768657265436f6e646974696f6e12110a096669656c644e616d651801" .
            "2001280912120a0a6669656c6456616c7565180220012809227a0a0e4f72" .
            "646572436f6e646974696f6e12110a096669656c644e616d651801200128" .
            "0912350a096f726465725479706518022001280e32222e636f6d6d6f6e70" .
            "622e4f72646572436f6e646974696f6e2e4f7264657254797065221e0a09" .
            "4f726465725479706512070a03415343100012080a044445534310012290" .
            "010a0a506167696e6174696f6e12100a087061676553697a651801200128" .
            "05120c0a047061676518022001280512300a0e6f72646572436f6e646974" .
            "696f6e18032003280b32182e636f6d6d6f6e70622e4f72646572436f6e64" .
            "6974696f6e12300a0e7768657265436f6e646974696f6e18042003280b32" .
            "182e636f6d6d6f6e70622e5768657265436f6e646974696f6e620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

