<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Commonpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * order 排序条件
 *
 * Generated from protobuf message <code>commonpb.OrderCondition</code>
 */
class OrderCondition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fieldName = 1;</code>
     */
    private $fieldName = '';
    /**
     * Generated from protobuf field <code>.commonpb.OrderCondition.OrderType orderType = 2;</code>
     */
    private $orderType = 0;

    public function __construct() {
        \GPBMetadata\Common::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string fieldName = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->fieldName;
    }

    /**
     * Generated from protobuf field <code>string fieldName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->fieldName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.commonpb.OrderCondition.OrderType orderType = 2;</code>
     * @return int
     */
    public function getOrderType()
    {
        return $this->orderType;
    }

    /**
     * Generated from protobuf field <code>.commonpb.OrderCondition.OrderType orderType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkEnum($var, \Commonpb\OrderCondition_OrderType::class);
        $this->orderType = $var;

        return $this;
    }

}

