<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Commonpb;

/**
 * Protobuf enum <code>Commonpb\OrderCondition\OrderType</code>
 */
class OrderCondition_OrderType
{
    /**
     * Generated from protobuf enum <code>ASC = 0;</code>
     */
    const ASC = 0;
    /**
     * Generated from protobuf enum <code>DESC = 1;</code>
     */
    const DESC = 1;
}

