<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Commonpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 分页
 *
 * Generated from protobuf message <code>commonpb.Pagination</code>
 */
class Pagination extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 pageSize = 1;</code>
     */
    private $pageSize = 0;
    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>repeated .commonpb.OrderCondition orderCondition = 3;</code>
     */
    private $orderCondition;
    /**
     * Generated from protobuf field <code>repeated .commonpb.WhereCondition whereCondition = 4;</code>
     */
    private $whereCondition;

    public function __construct() {
        \GPBMetadata\Common::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 1;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pageSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .commonpb.OrderCondition orderCondition = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderCondition()
    {
        return $this->orderCondition;
    }

    /**
     * Generated from protobuf field <code>repeated .commonpb.OrderCondition orderCondition = 3;</code>
     * @param \Commonpb\OrderCondition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderCondition($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Commonpb\OrderCondition::class);
        $this->orderCondition = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .commonpb.WhereCondition whereCondition = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWhereCondition()
    {
        return $this->whereCondition;
    }

    /**
     * Generated from protobuf field <code>repeated .commonpb.WhereCondition whereCondition = 4;</code>
     * @param \Commonpb\WhereCondition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWhereCondition($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Commonpb\WhereCondition::class);
        $this->whereCondition = $arr;

        return $this;
    }

}

