<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

namespace Smspb;

/**
 * mark 枚举 操作
 *
 * Protobuf enum <code>Smspb\Marks</code>
 */
class Marks
{
    /**
     * 登录
     *
     * Generated from protobuf enum <code>LOGIN = 0;</code>
     */
    const LOGIN = 0;
}

