<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

namespace Smspb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>smspb.SmsListRequest</code>
 */
class SmsListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 手机号
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     */
    private $phone = '';
    /**
     * Generated from protobuf field <code>.commonpb.Pagination pagination = 2;</code>
     */
    private $pagination = null;

    public function __construct() {
        \GPBMetadata\Sms::initOnce();
        parent::__construct();
    }

    /**
     * 手机号
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * 手机号
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.commonpb.Pagination pagination = 2;</code>
     * @return \Commonpb\Pagination
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    /**
     * Generated from protobuf field <code>.commonpb.Pagination pagination = 2;</code>
     * @param \Commonpb\Pagination $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Commonpb\Pagination::class);
        $this->pagination = $var;

        return $this;
    }

}

