<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

namespace Smspb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>smspb.SmsList</code>
 */
class SmsList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .smspb.SmsInfo smsInfo = 1;</code>
     */
    private $smsInfo;

    public function __construct() {
        \GPBMetadata\Sms::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .smspb.SmsInfo smsInfo = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSmsInfo()
    {
        return $this->smsInfo;
    }

    /**
     * Generated from protobuf field <code>repeated .smspb.SmsInfo smsInfo = 1;</code>
     * @param \Smspb\SmsInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSmsInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Smspb\SmsInfo::class);
        $this->smsInfo = $arr;

        return $this;
    }

}

