<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

namespace Smspb;

/**
 * 验证码状态
 *
 * Protobuf enum <code>Smspb\SmsStatus</code>
 */
class SmsStatus
{
    /**
     * Generated from protobuf enum <code>STATUS_NONE = 0;</code>
     */
    const STATUS_NONE = 0;
    /**
     * Generated from protobuf enum <code>STATUS_FAIL = 1;</code>
     */
    const STATUS_FAIL = 1;
    /**
     * Generated from protobuf enum <code>STATUS_SUCC = 2;</code>
     */
    const STATUS_SUCC = 2;


    function test(){
        var_dump($a);
    }


}

