<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

namespace Smspb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>smspb.VerifyCodeRequest</code>
 */
class VerifyCodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 手机号
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     */
    private $phone = '';
    /**
     * 用户id
     *
     * Generated from protobuf field <code>string guid = 2;</code>
     */
    private $guid = '';
    /**
     * 登陆token
     *
     * Generated from protobuf field <code>string gtoken = 3;</code>
     */
    private $gtoken = '';
    /**
     * gtoken有效时间截止时间
     *
     * Generated from protobuf field <code>int32 deadline = 4;</code>
     */
    private $deadline = 0;
    /**
     * 操作(枚举)
     *
     * Generated from protobuf field <code>.smspb.Marks mark = 5;</code>
     */
    private $mark = 0;

    public function __construct() {
        \GPBMetadata\Sms::initOnce();
        parent::__construct();
    }

    /**
     * 手机号
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * 手机号
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>string guid = 2;</code>
     * @return string
     */
    public function getGuid()
    {
        return $this->guid;
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>string guid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->guid = $var;

        return $this;
    }

    /**
     * 登陆token
     *
     * Generated from protobuf field <code>string gtoken = 3;</code>
     * @return string
     */
    public function getGtoken()
    {
        return $this->gtoken;
    }

    /**
     * 登陆token
     *
     * Generated from protobuf field <code>string gtoken = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGtoken($var)
    {
        GPBUtil::checkString($var, True);
        $this->gtoken = $var;

        return $this;
    }

    /**
     * gtoken有效时间截止时间
     *
     * Generated from protobuf field <code>int32 deadline = 4;</code>
     * @return int
     */
    public function getDeadline()
    {
        return $this->deadline;
    }

    /**
     * gtoken有效时间截止时间
     *
     * Generated from protobuf field <code>int32 deadline = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDeadline($var)
    {
        GPBUtil::checkInt32($var);
        $this->deadline = $var;

        return $this;
    }

    /**
     * 操作(枚举)
     *
     * Generated from protobuf field <code>.smspb.Marks mark = 5;</code>
     * @return int
     */
    public function getMark()
    {
        return $this->mark;
    }

    /**
     * 操作(枚举)
     *
     * Generated from protobuf field <code>.smspb.Marks mark = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMark($var)
    {
        GPBUtil::checkEnum($var, \Smspb\Marks::class);
        $this->mark = $var;

        return $this;
    }

}

