<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

namespace Smspb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>smspb.VerifyCodeReply</code>
 */
class VerifyCodeReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 valid_time = 1;</code>
     */
    private $valid_time = 0;
    /**
     * Generated from protobuf field <code>string seed = 2;</code>
     */
    private $seed = '';

    public function __construct() {
        \GPBMetadata\Sms::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 valid_time = 1;</code>
     * @return int
     */
    public function getValidTime()
    {
        return $this->valid_time;
    }

    /**
     * Generated from protobuf field <code>int32 valid_time = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setValidTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->valid_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string seed = 2;</code>
     * @return string
     */
    public function getSeed()
    {
        return $this->seed;
    }

    /**
     * Generated from protobuf field <code>string seed = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSeed($var)
    {
        GPBUtil::checkString($var, True);
        $this->seed = $var;

        return $this;
    }


    const sdfsdfsdf = '121212';



}

